#!/bin/bash 
 #project name and direcotry
 name=projname 
 root=~/Documents/prog/ 
 
 #panes with 'pane1_cmd:pane2_cmd,layout'
 main_panes='nvim:zsh,main-vertical'
 
 
 
 
 # additional windows 
 #Always put the window definition inside '' like and example above. 
 
 #windows=('window_cmd:pane1_cmd'.'window2_cmd:pane2_cmd') 
 #each window definition is seperated by . 
 windows=('python:gdb,main-vertical'.'zsh,main-vertical') 
 

